{"uuid":"196f67c9-3734-486c-a961-872f66b3a148","historyId":"acb97a71ebe53a747a1d7b5144fd0c5f","fullName":"org.example.tests.LoginTest.loginInvalidTest","labels":[{"name":"package","value":"org.example.tests.LoginTest"},{"name":"testClass","value":"org.example.tests.LoginTest"},{"name":"testMethod","value":"loginInvalidTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Practica_Introduction"},{"name":"subSuite","value":"org.example.tests.LoginTest"},{"name":"host","value":"Mex-US-0-0"},{"name":"thread","value":"16752@Mex-US-0-0.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"loginInvalidTest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"El inicio de sesion no fue falso expected [Credenciales incorrectas] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]","trace":"java.lang.AssertionError: El inicio de sesion no fue falso expected [Credenciales incorrectas] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.example.tests.LoginTest.verifyLoginFailure(LoginTest.java:54)\r\n\tat org.example.tests.LoginTest.loginInvalidTest(LoginTest.java:33)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Prueba de inicio de sesion con credenciales invalidas","steps":[],"attachments":[],"parameters":[],"start":1741371632836,"stop":1741371635593}